### ISSUE TITLE
Trigonometry

### ISSUE THREAD

**Issue by tdhc153** [tdhc153/starmast#8]
Content of guide: 
* definition of cos, sin, tan in terms of the circle,
* common angles and values of cos, sin, tan at these angles,
* properties of sin, cos, tan

- [ ] Study guide
- [ ] Questions
- [ ] Answers

**Comment by ccsa357** [comment]
Content Outline: 
* Authors and Summary
* Introduction
* definition of cos, sin, tan in terms of the circle
  * Show unit circle, with diagrams  
* common angles values of cos, sin, tan at these angles,
  * Insert table 
* properties of sin, cos, tan
